version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./WebAPI/WebAPI/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=administration_database;Username=postgres;Password=password
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: administration_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  reactapp:
    image: ${DOCKER_REGISTRY-}reactapp
    build:
        context: ./ReactSamplePage/react_log_page
        dockerfile: Dockerfile
    ports:
        - "3000:3000"
           